package(default_visibility = ["//visibility:public"])

java_library(
    name = "interceptors",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_dagger//:dagger_with_compiler",
        "@grpc_java//core",
    ],
)
